name: Workshop CI Menotoria 

# [script de pipeline] YAML 
# [gatilhos] (manual, agendada, quando houver mudanças, etc.) 
on:
  workflow_dispatch:

jobs:
  tests:
    # [config do sistema operacional] (mac/windows/linux/etc) 
    runs-on: ubuntu-latest

    # [variaveis] (de ambiente, chaves de acesso) 
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    steps:
      # [projetos] (aplicacoes FE/BE, apps, projetos de testes, etc) 
      - name: Clone do projeto
        uses: actions/checkout@v4

      # [dependencias do projeto] (node/npm, java/maven, python/pip) 
      - name: Instalando deps do projeto
        run: npm install

      - name: Iniciando servidor Mock
        run: npm run mock-server &

      - name: Iniciando servidor da aplicação
        run: npm run server &

      # [acoes para verificar regras/políticas] (cobertura de código, formatacao, testes ui/e2e/unit/etc.) 
      - name: Executando sos testes e2e do projeto
        run: npx cypress run
